Rename ignore_handler_s to avoid conflict with libc
Source/Lib/Codec/EbEncHandle.c:135:13: error: static declaration of 'ignore_handler_s' follows non-static declaration
static void ignore_handler_s(const char *msg, void *ptr, errno_t error)
            ^
/usr/include/stdlib.h:342:6: note: previous declaration is here
void ignore_handler_s(const char * __restrict, void * __restrict, errno_t);
     ^