Fix an issue that ffmpeg patch files could not be applied
configure has been changed.
https://github.com/FFmpeg/FFmpeg/commit/f32f56468c6caa03f4ebbf6cf58b2bb7bc775216
So there is an error:
error: patch failed: configure:3315
error: configure: patch does not apply
This change fixes this error.

Signed-off-by: kusaanko <39370373+kusaanko@users.noreply.github.com>